In [1]:
import pandas as pd

In [ ]:
#extraemos el archivo que nos paso el cliente
ruta_archivo = "ventas_distribuidora_caos.csv"
df_datosSucios = pd.read_csv(ruta_archivo)

In [3]:
df_datosSucios.head()

,id_venta,fecha_venta,cliente,provincia,sku,producto,cantidad,precio_unitario,monto_total,metodo_pago,estado_pago
0,V1001,2026-05-02,juan perez,Buenos Aires,F001,Tornillos caja x100,2,"$ 1.500,50","$ 3.001,00",Efectivo,Pagado
1,V1002,03/05/2026,Ferretería El Martillo,Córdoba,F002,Disco de corte,10,2500,25000,Transferencia,Pagado
2,V1003,"May 04, 2026",MARIA GOMEZ,Santa Fe,F003,Guantes de trabajo,4,"3.200,00","12.800,00",Tarjeta,Pagado
3,V1004,2026-05-05,Construcciones Sur,Buenos Aires,F004,Taladro eléctrico,1,"$ 85.000,00","$ 85.000,00",Cuenta corriente,Pendiente
4,V1005,06/05/2026,JUAN PEREZ,Bs. As.,F005,Cinta aisladora,6,1500,9000,NaN,Pagado

In [ ]:
#esta funcion es para poner de manera minuscula las columna que uno elige
df_datosSucios["cliente"] = df_datosSucios["cliente"].str.lower().str.strip()
df_datosSucios.head()

,id_venta,fecha_venta,cliente,provincia,sku,producto,cantidad,precio_unitario,monto_total,metodo_pago,estado_pago
0,V1001,2026-05-02,juan perez,Buenos Aires,F001,Tornillos caja x100,2,"$ 1.500,50","$ 3.001,00",Efectivo,Pagado
1,V1002,03/05/2026,ferretería el martillo,Córdoba,F002,Disco de corte,10,2500,25000,Transferencia,Pagado
2,V1003,"May 04, 2026",maria gomez,Santa Fe,F003,Guantes de trabajo,4,"3.200,00","12.800,00",Tarjeta,Pagado
3,V1004,2026-05-05,construcciones sur,Buenos Aires,F004,Taladro eléctrico,1,"$ 85.000,00","$ 85.000,00",Cuenta corriente,Pendiente
4,V1005,06/05/2026,juan perez,Bs. As.,F005,Cinta aisladora,6,1500,9000,NaN,Pagado

In [ ]:
#esta funcion es para agregar mayuscula en la primera letra
df_datosSucios["cliente"] = df_datosSucios["cliente"].astype(str).str.strip().str.capitalize()
df_datosSucios.head()

,id_venta,fecha_venta,cliente,provincia,sku,producto,cantidad,precio_unitario,monto_total,metodo_pago,estado_pago
0,V1001,2026-02-05,Juan perez,Buenos Aires,F001,Tornillos caja x100,2,"$ 1.500,50","$ 3.001,00",Efectivo,Pagado
1,V1002,2026-05-03,Ferretería el martillo,Córdoba,F002,Disco de corte,10,2500,25000,Transferencia,Pagado
2,V1003,2026-05-04,Maria gomez,Santa Fe,F003,Guantes de trabajo,4,"3.200,00","12.800,00",Tarjeta,Pagado
3,V1004,2026-05-05,Construcciones sur,Buenos Aires,F004,Taladro eléctrico,1,"$ 85.000,00","$ 85.000,00",Cuenta corriente,Pendiente
4,V1005,2026-05-06,Juan perez,Bs. As.,F005,Cinta aisladora,6,1500,9000,NaN,Pagado

In [ ]:
# funcion para ordenar las fechas
df_datosSucios["fecha_venta"] = pd.to_datetime(
    df_datosSucios["fecha_venta"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)
df_datosSucios.head()

,id_venta,fecha_venta,cliente,provincia,sku,producto,cantidad,precio_unitario,monto_total,metodo_pago,estado_pago
0,V1001,2026-02-05,Juan perez,Buenos Aires,F001,Tornillos caja x100,2,"$ 1.500,50","$ 3.001,00",Efectivo,Pagado
1,V1002,2026-05-03,Ferretería el martillo,Córdoba,F002,Disco de corte,10,2500,25000,Transferencia,Pagado
2,V1003,2026-05-04,Maria gomez,Santa Fe,F003,Guantes de trabajo,4,"3.200,00","12.800,00",Tarjeta,Pagado
3,V1004,2026-05-05,Construcciones sur,Buenos Aires,F004,Taladro eléctrico,1,"$ 85.000,00","$ 85.000,00",Cuenta corriente,Pendiente
4,V1005,2026-05-06,Juan perez,Bs. As.,F005,Cinta aisladora,6,1500,9000,NaN,Pagado

In [ ]:
# Primero limpiamos espacios y dejamos un formato base
df_datosSucios["provincia"] = df_datosSucios["provincia"].astype(str).str.strip()

# Creamos un diccionario para reemplazar las variantes por el nombre oficial
mapeo_provincias = {
    "Bs. As.": "Buenos Aires",
    "bs. as.": "Buenos Aires",
    "BS. AS.": "Buenos Aires",
    "Bs As": "Buenos Aires"
}

# Aplicamos el reemplazo en la columna
df_datosSucios["provincia"] = df_datosSucios["provincia"].replace(mapeo_provincias)

df_datosSucios.head(15)

,id_venta,fecha_venta,cliente,provincia,sku,producto,cantidad,precio_unitario,monto_total,metodo_pago,estado_pago
0,V1001,2026-02-05,Juan perez,Buenos Aires,F001,Tornillos caja x100,2,"$ 1.500,50","$ 3.001,00",Efectivo,Pagado
1,V1002,2026-05-03,Ferretería el martillo,Córdoba,F002,Disco de corte,10,2500,25000,Transferencia,Pagado
2,V1003,2026-05-04,Maria gomez,Santa Fe,F003,Guantes de trabajo,4,"3.200,00","12.800,00",Tarjeta,Pagado
3,V1004,2026-05-05,Construcciones sur,Buenos Aires,F004,Taladro eléctrico,1,"$ 85.000,00","$ 85.000,00",Cuenta corriente,Pendiente
4,V1005,2026-05-06,Juan perez,Buenos Aires,F005,Cinta aisladora,6,1500,9000,NaN,Pagado
5,V1006,2026-07-05,Ferreteria el martillo,Cordoba,F001,Tornillos caja x100,5,"1,500.50","7,502.50",transferencia,Pagado
6,V1007,NaT,María gómez,NaN,F002,Disco de corte,3,$ 2.500,$ 7.500,Efectivo,Pagado
7,V1008,2026-05-08,Electricidad lópez,Entre Ríos,F005,Cinta aisladora,12,"ARS 1.500,00","ARS 18.000,00",Transferencia,Pendiente
8,V1009,2026-09-05,Construcciones sur,Buenos Aires,F006,Martillo,2,12500,NaN,Cuenta corriente,Pendiente
9,V1010,2026-05-10,Juan pérez,Buenos Aires,F003,Guantes de trabajo,2,"$ 3.200,00","$ 6.400,00",efectivo,Pagado
10,V1011,2026-05-11,Pinturería color norte,Mendoza,F007,Pintura látex 4L,3,"18.500,75","55.502,25",Tarjeta,Pagado
11,V1012,2026-05-12,Maria gomez,Santa Fe,F006,Martillo,1,12500,12500,NaN,Pendiente
12,V1013,NaT,Ferreteria el martillo,Córdoba,F004,Taladro eléctrico,1,"$ 85.000,00",-,Transferencia,Pagado
13,V1014,2026-05-13,Electricidad lopez,Entre Rios,F008,Cable rollo 100m,2,"45,000.00","90,000.00",TRANSFERENCIA,Pagado
14,V1015,2026-05-14,Corralón san josé,NaN,F001,Tornillos caja x100,8,"$ 1.500,50","$ 12.004,00",Cuenta corriente,Pendiente

In [11]:
# Primero limpiamos espacios y dejamos un formato base
df_datosSucios["metodo_pago"] = df_datosSucios["metodo_pago"].astype(str).str.strip()
#esta funcion es para poner de manera minuscula las columna que uno elige
df_datosSucios["metodo_pago"] = df_datosSucios["metodo_pago"].str.lower().str.strip()
#esta funcion es para agregar mayuscula en la primera letra
df_datosSucios["metodo_pago"] = df_datosSucios["metodo_pago"].astype(str).str.strip().str.capitalize()
df_datosSucios.head(10)

,id_venta,fecha_venta,cliente,provincia,sku,producto,cantidad,precio_unitario,monto_total,metodo_pago,estado_pago
0,V1001,2026-02-05,Juan perez,Buenos Aires,F001,Tornillos caja x100,2,"$ 1.500,50","$ 3.001,00",Efectivo,Pagado
1,V1002,2026-05-03,Ferretería el martillo,Córdoba,F002,Disco de corte,10,2500,25000,Transferencia,Pagado
2,V1003,2026-05-04,Maria gomez,Santa Fe,F003,Guantes de trabajo,4,"3.200,00","12.800,00",Tarjeta,Pagado
3,V1004,2026-05-05,Construcciones sur,Buenos Aires,F004,Taladro eléctrico,1,"$ 85.000,00","$ 85.000,00",Cuenta corriente,Pendiente
4,V1005,2026-05-06,Juan perez,Buenos Aires,F005,Cinta aisladora,6,1500,9000,NaN,Pagado
5,V1006,2026-07-05,Ferreteria el martillo,Cordoba,F001,Tornillos caja x100,5,"1,500.50","7,502.50",Transferencia,Pagado
6,V1007,NaT,María gómez,NaN,F002,Disco de corte,3,$ 2.500,$ 7.500,Efectivo,Pagado
7,V1008,2026-05-08,Electricidad lópez,Entre Ríos,F005,Cinta aisladora,12,"ARS 1.500,00","ARS 18.000,00",Transferencia,Pendiente
8,V1009,2026-09-05,Construcciones sur,Buenos Aires,F006,Martillo,2,12500,NaN,Cuenta corriente,Pendiente
9,V1010,2026-05-10,Juan pérez,Buenos Aires,F003,Guantes de trabajo,2,"$ 3.200,00","$ 6.400,00",Efectivo,Pagado

In [12]:
# Te muestra los tipos de datos de cada columna
df_datosSucios.dtypes

id_venta                      str
fecha_venta        datetime64[us]
cliente                       str
provincia                     str
sku                           str
producto                      str
cantidad                    int64
precio_unitario               str
monto_total                   str
metodo_pago                   str
estado_pago                   str
dtype: object

In [13]:
# Ver los métodos de pago y cuántas veces se repite cada uno (incluyendo nulos)
print("--- METODOS DE PAGO ---")
print(df_datosSucios["metodo_pago"].value_counts(dropna=False))

print("\n--- ESTADOS DE PAGO ---")
print(df_datosSucios["estado_pago"].value_counts(dropna=False))

--- METODOS DE PAGO ---
metodo_pago
Transferencia       13
Efectivo             9
Tarjeta              7
Cuenta corriente     7
NaN                  4
Name: count, dtype: int64

--- ESTADOS DE PAGO ---
estado_pago
Pagado       29
Pendiente    11
Name: count, dtype: int64

In [15]:
df_datosSucios["metodo_pago"] = df_datosSucios["metodo_pago"].fillna("No especificado")
df_datosSucios.head(10)

,id_venta,fecha_venta,cliente,provincia,sku,producto,cantidad,precio_unitario,monto_total,metodo_pago,estado_pago
0,V1001,2026-02-05,Juan perez,Buenos Aires,F001,Tornillos caja x100,2,"$ 1.500,50","$ 3.001,00",Efectivo,Pagado
1,V1002,2026-05-03,Ferretería el martillo,Córdoba,F002,Disco de corte,10,2500,25000,Transferencia,Pagado
2,V1003,2026-05-04,Maria gomez,Santa Fe,F003,Guantes de trabajo,4,"3.200,00","12.800,00",Tarjeta,Pagado
3,V1004,2026-05-05,Construcciones sur,Buenos Aires,F004,Taladro eléctrico,1,"$ 85.000,00","$ 85.000,00",Cuenta corriente,Pendiente
4,V1005,2026-05-06,Juan perez,Buenos Aires,F005,Cinta aisladora,6,1500,9000,No especificado,Pagado
5,V1006,2026-07-05,Ferreteria el martillo,Cordoba,F001,Tornillos caja x100,5,"1,500.50","7,502.50",Transferencia,Pagado
6,V1007,NaT,María gómez,NaN,F002,Disco de corte,3,$ 2.500,$ 7.500,Efectivo,Pagado
7,V1008,2026-05-08,Electricidad lópez,Entre Ríos,F005,Cinta aisladora,12,"ARS 1.500,00","ARS 18.000,00",Transferencia,Pendiente
8,V1009,2026-09-05,Construcciones sur,Buenos Aires,F006,Martillo,2,12500,NaN,Cuenta corriente,Pendiente
9,V1010,2026-05-10,Juan pérez,Buenos Aires,F003,Guantes de trabajo,2,"$ 3.200,00","$ 6.400,00",Efectivo,Pagado

In [16]:
import numpy as np

def limpiar_moneda(serie):
    # 1. Convertimos a texto por las dudas, reemplazamos valores nulos por texto vacío temporalmente
    serie_str = serie.astype(str).str.replace("nan", "", case=False)
    
    # 2. Sacamos las letras (como 'ARS') y los símbolos '$'
    serie_limpia = (
        serie_str
        .str.replace("ARS", "", case=False, regex=False)
        .str.replace("$", "", regex=False)
    )
    
    # 3. Manejamos los puntos y comas de manera inteligente:
    # Si tiene un punto como miles y una coma como decimal (ej: 1.500,50)
    # Primero sacamos los puntos de miles y después cambiamos la coma decimal por punto.
    serie_limpia = (
        serie_limpia
        .str.replace(".", "", regex=False)    # Saca el punto de miles
        .str.replace(",", ".", regex=False)  # Cambia la coma por punto para que Python/SQL lo entienda como decimal
        .str.strip()                         # Saca espacios vacíos sobrantes
    )
    
    # 4. Convertimos a numérico: lo que no se pueda convertir (como celdas vacías), lo transforma en NaN (número nulo)
    return pd.to_numeric(serie_limpia, errors="coerce")

# Aplicamos la función a tus dos columnas problemáticas
df_datosSucios["precio_unitario"] = limpiar_moneda(df_datosSucios["precio_unitario"])
df_datosSucios["monto_total"] = limpiar_moneda(df_datosSucios["monto_total"])

df_datosSucios.head(10)

,id_venta,fecha_venta,cliente,provincia,sku,producto,cantidad,precio_unitario,monto_total,metodo_pago,estado_pago
0,V1001,2026-02-05,Juan perez,Buenos Aires,F001,Tornillos caja x100,2,1500.5000,3001.0000,Efectivo,Pagado
1,V1002,2026-05-03,Ferretería el martillo,Córdoba,F002,Disco de corte,10,2500.0000,25000.0000,Transferencia,Pagado
2,V1003,2026-05-04,Maria gomez,Santa Fe,F003,Guantes de trabajo,4,3200.0000,12800.0000,Tarjeta,Pagado
3,V1004,2026-05-05,Construcciones sur,Buenos Aires,F004,Taladro eléctrico,1,85000.0000,85000.0000,Cuenta corriente,Pendiente
4,V1005,2026-05-06,Juan perez,Buenos Aires,F005,Cinta aisladora,6,1500.0000,9000.0000,No especificado,Pagado
5,V1006,2026-07-05,Ferreteria el martillo,Cordoba,F001,Tornillos caja x100,5,1.5005,7.5025,Transferencia,Pagado
6,V1007,NaT,María gómez,NaN,F002,Disco de corte,3,2500.0000,7500.0000,Efectivo,Pagado
7,V1008,2026-05-08,Electricidad lópez,Entre Ríos,F005,Cinta aisladora,12,1500.0000,18000.0000,Transferencia,Pendiente
8,V1009,2026-09-05,Construcciones sur,Buenos Aires,F006,Martillo,2,12500.0000,NaN,Cuenta corriente,Pendiente
9,V1010,2026-05-10,Juan pérez,Buenos Aires,F003,Guantes de trabajo,2,3200.0000,6400.0000,Efectivo,Pagado

In [17]:
df_datosSucios = df_datosSucios.drop_duplicates()
df_datosSucios.head(10)

,id_venta,fecha_venta,cliente,provincia,sku,producto,cantidad,precio_unitario,monto_total,metodo_pago,estado_pago
0,V1001,2026-02-05,Juan perez,Buenos Aires,F001,Tornillos caja x100,2,1500.5000,3001.0000,Efectivo,Pagado
1,V1002,2026-05-03,Ferretería el martillo,Córdoba,F002,Disco de corte,10,2500.0000,25000.0000,Transferencia,Pagado
2,V1003,2026-05-04,Maria gomez,Santa Fe,F003,Guantes de trabajo,4,3200.0000,12800.0000,Tarjeta,Pagado
3,V1004,2026-05-05,Construcciones sur,Buenos Aires,F004,Taladro eléctrico,1,85000.0000,85000.0000,Cuenta corriente,Pendiente
4,V1005,2026-05-06,Juan perez,Buenos Aires,F005,Cinta aisladora,6,1500.0000,9000.0000,No especificado,Pagado
5,V1006,2026-07-05,Ferreteria el martillo,Cordoba,F001,Tornillos caja x100,5,1.5005,7.5025,Transferencia,Pagado
6,V1007,NaT,María gómez,NaN,F002,Disco de corte,3,2500.0000,7500.0000,Efectivo,Pagado
7,V1008,2026-05-08,Electricidad lópez,Entre Ríos,F005,Cinta aisladora,12,1500.0000,18000.0000,Transferencia,Pendiente
8,V1009,2026-09-05,Construcciones sur,Buenos Aires,F006,Martillo,2,12500.0000,NaN,Cuenta corriente,Pendiente
9,V1010,2026-05-10,Juan pérez,Buenos Aires,F003,Guantes de trabajo,2,3200.0000,6400.0000,Efectivo,Pagado

In [18]:
# Te muestra los tipos de datos de cada columna
df_datosSucios.dtypes

id_venta                      str
fecha_venta        datetime64[us]
cliente                       str
provincia                     str
sku                           str
producto                      str
cantidad                    int64
precio_unitario           float64
monto_total               float64
metodo_pago                   str
estado_pago                   str
dtype: object

In [19]:
# 1. Limpiamos espacios, pasamos a formato Título (primera letra en mayúscula)
df_datosSucios["cliente"] = (
    df_datosSucios["cliente"]
    .astype(str)
    .str.strip()
    .str.title()
)

# 2. Mostramos cómo quedó la columna cliente actualizada
print(df_datosSucios[["id_venta", "cliente"]])

   id_venta                 cliente
0     V1001              Juan Perez
1     V1002  Ferretería El Martillo
2     V1003             Maria Gomez
3     V1004      Construcciones Sur
4     V1005              Juan Perez
5     V1006  Ferreteria El Martillo
6     V1007             María Gómez
7     V1008      Electricidad López
8     V1009      Construcciones Sur
9     V1010              Juan Pérez
10    V1011  Pinturería Color Norte
11    V1012             Maria Gomez
12    V1013  Ferreteria El Martillo
13    V1014      Electricidad Lopez
14    V1015       Corralón San José
15    V1016              Juan Pérez
16    V1017  Pintureria Color Norte
17    V1018      Construcciones Sur
18    V1019             María Gómez
19    V1020       Corralon San Jose
20    V1021  Ferretería El Martillo
21    V1022      Electricidad Lopez
22    V1023              Juan Perez
23    V1024  Pintureria Color Norte
24    V1025       Corralón San José
25    V1026             Maria Gomez
26    V1027      Construcciones Sur
27    V1028  Ferretería El Martillo
28    V1029      Electricidad López
29    V1030              Juan Perez
30    V1031  Pintureria Color Norte
31    V1032       Corralon San Jose
32    V1033             María Gómez
33    V1034      Construcciones Sur
34    V1035  Ferretería El Martillo
35    V1036      Electricidad Lopez

In [20]:
import unicodedata

def limpiar_nombre_cliente(texto):
    if pd.isna(texto):
        return texto
    
    # 1. Normaliza el texto para separar las letras de sus tildes
    nfkd_form = unicodedata.normalize('NFKD', str(texto))
    
    # 2. Filtra y elimina los caracteres de acentuación (combining characters)
    sin_tildes = "".join([c for c in nfkd_form if not unicodedata.combining(c)])
    
    # 3. Devuelve el texto limpio, sin espacios extra y en formato título (Ej: "Maria Gomez")
    return sin_tildes.strip().title()

# Aplicamos la función a la columna cliente
df_datosSucios["cliente"] = df_datosSucios["cliente"].apply(limpiar_nombre_cliente)

# Verificamos cómo quedó la columna
print(df_datosSucios[["id_venta", "cliente"]])

   id_venta                 cliente
0     V1001              Juan Perez
1     V1002  Ferreteria El Martillo
2     V1003             Maria Gomez
3     V1004      Construcciones Sur
4     V1005              Juan Perez
5     V1006  Ferreteria El Martillo
6     V1007             Maria Gomez
7     V1008      Electricidad Lopez
8     V1009      Construcciones Sur
9     V1010              Juan Perez
10    V1011  Pintureria Color Norte
11    V1012             Maria Gomez
12    V1013  Ferreteria El Martillo
13    V1014      Electricidad Lopez
14    V1015       Corralon San Jose
15    V1016              Juan Perez
16    V1017  Pintureria Color Norte
17    V1018      Construcciones Sur
18    V1019             Maria Gomez
19    V1020       Corralon San Jose
20    V1021  Ferreteria El Martillo
21    V1022      Electricidad Lopez
22    V1023              Juan Perez
23    V1024  Pintureria Color Norte
24    V1025       Corralon San Jose
25    V1026             Maria Gomez
26    V1027      Construcciones Sur
27    V1028  Ferreteria El Martillo
28    V1029      Electricidad Lopez
29    V1030              Juan Perez
30    V1031  Pintureria Color Norte
31    V1032       Corralon San Jose
32    V1033             Maria Gomez
33    V1034      Construcciones Sur
34    V1035  Ferreteria El Martillo
35    V1036      Electricidad Lopez

In [21]:
df_datosSucios.head(10)

,id_venta,fecha_venta,cliente,provincia,sku,producto,cantidad,precio_unitario,monto_total,metodo_pago,estado_pago
0,V1001,2026-02-05,Juan Perez,Buenos Aires,F001,Tornillos caja x100,2,1500.5000,3001.0000,Efectivo,Pagado
1,V1002,2026-05-03,Ferreteria El Martillo,Córdoba,F002,Disco de corte,10,2500.0000,25000.0000,Transferencia,Pagado
2,V1003,2026-05-04,Maria Gomez,Santa Fe,F003,Guantes de trabajo,4,3200.0000,12800.0000,Tarjeta,Pagado
3,V1004,2026-05-05,Construcciones Sur,Buenos Aires,F004,Taladro eléctrico,1,85000.0000,85000.0000,Cuenta corriente,Pendiente
4,V1005,2026-05-06,Juan Perez,Buenos Aires,F005,Cinta aisladora,6,1500.0000,9000.0000,No especificado,Pagado
5,V1006,2026-07-05,Ferreteria El Martillo,Cordoba,F001,Tornillos caja x100,5,1.5005,7.5025,Transferencia,Pagado
6,V1007,NaT,Maria Gomez,NaN,F002,Disco de corte,3,2500.0000,7500.0000,Efectivo,Pagado
7,V1008,2026-05-08,Electricidad Lopez,Entre Ríos,F005,Cinta aisladora,12,1500.0000,18000.0000,Transferencia,Pendiente
8,V1009,2026-09-05,Construcciones Sur,Buenos Aires,F006,Martillo,2,12500.0000,NaN,Cuenta corriente,Pendiente
9,V1010,2026-05-10,Juan Perez,Buenos Aires,F003,Guantes de trabajo,2,3200.0000,6400.0000,Efectivo,Pagado

In [22]:
# Rellenar NaN en monto_total usando cantidad * precio_unitario
df_datosSucios["monto_total"] = df_datosSucios["monto_total"].fillna(
    df_datosSucios["cantidad"] * df_datosSucios["precio_unitario"]
)

df_datosSucios.head(10)

,id_venta,fecha_venta,cliente,provincia,sku,producto,cantidad,precio_unitario,monto_total,metodo_pago,estado_pago
0,V1001,2026-02-05,Juan Perez,Buenos Aires,F001,Tornillos caja x100,2,1500.5000,3001.0000,Efectivo,Pagado
1,V1002,2026-05-03,Ferreteria El Martillo,Córdoba,F002,Disco de corte,10,2500.0000,25000.0000,Transferencia,Pagado
2,V1003,2026-05-04,Maria Gomez,Santa Fe,F003,Guantes de trabajo,4,3200.0000,12800.0000,Tarjeta,Pagado
3,V1004,2026-05-05,Construcciones Sur,Buenos Aires,F004,Taladro eléctrico,1,85000.0000,85000.0000,Cuenta corriente,Pendiente
4,V1005,2026-05-06,Juan Perez,Buenos Aires,F005,Cinta aisladora,6,1500.0000,9000.0000,No especificado,Pagado
5,V1006,2026-07-05,Ferreteria El Martillo,Cordoba,F001,Tornillos caja x100,5,1.5005,7.5025,Transferencia,Pagado
6,V1007,NaT,Maria Gomez,NaN,F002,Disco de corte,3,2500.0000,7500.0000,Efectivo,Pagado
7,V1008,2026-05-08,Electricidad Lopez,Entre Ríos,F005,Cinta aisladora,12,1500.0000,18000.0000,Transferencia,Pendiente
8,V1009,2026-09-05,Construcciones Sur,Buenos Aires,F006,Martillo,2,12500.0000,25000.0000,Cuenta corriente,Pendiente
9,V1010,2026-05-10,Juan Perez,Buenos Aires,F003,Guantes de trabajo,2,3200.0000,6400.0000,Efectivo,Pagado

In [24]:
# Corregir de forma quirúrgica el precio unitario y monto total de la fila V1006 (índice 5)
df_datosSucios.loc[df_datosSucios["id_venta"] == "V1006", "precio_unitario"] = 1500.50
df_datosSucios.loc[df_datosSucios["id_venta"] == "V1006", "monto_total"] = 5 * 1500.50  # cantidad (5) * precio unitario

df_datosSucios.head(20)

,id_venta,fecha_venta,cliente,provincia,sku,producto,cantidad,precio_unitario,monto_total,metodo_pago,estado_pago
0,V1001,2026-02-05,Juan Perez,Buenos Aires,F001,Tornillos caja x100,2,1500.50,3001.00,Efectivo,Pagado
1,V1002,2026-05-03,Ferreteria El Martillo,Córdoba,F002,Disco de corte,10,2500.00,25000.00,Transferencia,Pagado
2,V1003,2026-05-04,Maria Gomez,Santa Fe,F003,Guantes de trabajo,4,3200.00,12800.00,Tarjeta,Pagado
3,V1004,2026-05-05,Construcciones Sur,Buenos Aires,F004,Taladro eléctrico,1,85000.00,85000.00,Cuenta corriente,Pendiente
4,V1005,2026-05-06,Juan Perez,Buenos Aires,F005,Cinta aisladora,6,1500.00,9000.00,No especificado,Pagado
5,V1006,2026-07-05,Ferreteria El Martillo,Cordoba,F001,Tornillos caja x100,5,1500.50,7502.50,Transferencia,Pagado
6,V1007,NaT,Maria Gomez,NaN,F002,Disco de corte,3,2500.00,7500.00,Efectivo,Pagado
7,V1008,2026-05-08,Electricidad Lopez,Entre Ríos,F005,Cinta aisladora,12,1500.00,18000.00,Transferencia,Pendiente
8,V1009,2026-09-05,Construcciones Sur,Buenos Aires,F006,Martillo,2,12500.00,25000.00,Cuenta corriente,Pendiente
9,V1010,2026-05-10,Juan Perez,Buenos Aires,F003,Guantes de trabajo,2,3200.00,6400.00,Efectivo,Pagado
10,V1011,2026-05-11,Pintureria Color Norte,Mendoza,F007,Pintura látex 4L,3,18500.75,55502.25,Tarjeta,Pagado
11,V1012,2026-05-12,Maria Gomez,Santa Fe,F006,Martillo,1,12500.00,12500.00,No especificado,Pendiente
12,V1013,NaT,Ferreteria El Martillo,Córdoba,F004,Taladro eléctrico,1,85000.00,85000.00,Transferencia,Pagado
13,V1014,2026-05-13,Electricidad Lopez,Entre Rios,F008,Cable rollo 100m,2,45.00,90.00,Transferencia,Pagado
14,V1015,2026-05-14,Corralon San Jose,NaN,F001,Tornillos caja x100,8,1500.50,12004.00,Cuenta corriente,Pendiente
15,V1016,2026-05-15,Juan Perez,Buenos Aires,F002,Disco de corte,4,2500.00,10000.00,Tarjeta,Pagado
16,V1017,2026-05-16,Pintureria Color Norte,Mza.,F007,Pintura látex 4L,2,18500.75,37001.50,Efectivo,Pagado
17,V1018,2026-05-17,Construcciones Sur,Buenos Aires,F008,Cable rollo 100m,1,NaN,45000.00,Cuenta corriente,Pendiente
18,V1019,2026-05-18,Maria Gomez,Santa Fe,F005,Cinta aisladora,5,1500.00,7500.00,Transferencia,Pagado
19,V1020,2026-05-19,Corralon San Jose,Buenos Aires,F006,Martillo,3,12500.00,37500.00,No especificado,Pendiente

In [25]:
import unicodedata

def limpiar_provincia(texto):
    if pd.isna(texto):
        return texto  # Si es NaN, lo deja tranquilo para tratarlo después
    
    # 1. Quitar tildes
    nfkd_form = unicodedata.normalize('NFKD', str(texto))
    sin_tildes = "".join([c for c in nfkd_form if not unicodedata.combining(c)])
    
    # 2. Limpiar espacios y aplicar formato título
    return sin_tildes.strip().title()

# Aplicamos la función base para quitar tildes y normalizar formato
df_datosSucios["provincia"] = df_datosSucios["provincia"].apply(limpiar_provincia)

# 3. Diccionario de mapeo para unificar abreviaturas y variantes de provincias
mapeo_provincias = {
    "Mza.": "Mendoza",
    "Mza": "Mendoza",
    "Mdz": "Mendoza",
    "Bs. As.": "Buenos Aires",
    "Bs As": "Buenos Aires",
    "Bsas": "Buenos Aires"
}

df_datosSucios["provincia"] = df_datosSucios["provincia"].replace(mapeo_provincias)

# Verificamos los valores únicos de provincias para ver cómo quedó
print(df_datosSucios["provincia"].value_counts(dropna=False))

provincia
Buenos Aires    13
Cordoba          5
Santa Fe         5
Entre Rios       5
NaN              4
Mendoza          4
Name: count, dtype: int64

In [27]:
# Automatizar: Si el cliente es Maria Gomez y la provincia es NaN, ponerle Santa Fe en cualquier parte de la tabla
df_datosSucios.loc[
    (df_datosSucios["cliente"] == "Maria Gomez") & (df_datosSucios["provincia"].isna()), 
    "provincia"
] = "Santa Fe"


df_datosSucios.head(20)

,id_venta,fecha_venta,cliente,provincia,sku,producto,cantidad,precio_unitario,monto_total,metodo_pago,estado_pago
0,V1001,2026-02-05,Juan Perez,Buenos Aires,F001,Tornillos caja x100,2,1500.50,3001.00,Efectivo,Pagado
1,V1002,2026-05-03,Ferreteria El Martillo,Cordoba,F002,Disco de corte,10,2500.00,25000.00,Transferencia,Pagado
2,V1003,2026-05-04,Maria Gomez,Santa Fe,F003,Guantes de trabajo,4,3200.00,12800.00,Tarjeta,Pagado
3,V1004,2026-05-05,Construcciones Sur,Buenos Aires,F004,Taladro eléctrico,1,85000.00,85000.00,Cuenta corriente,Pendiente
4,V1005,2026-05-06,Juan Perez,Buenos Aires,F005,Cinta aisladora,6,1500.00,9000.00,No especificado,Pagado
5,V1006,2026-07-05,Ferreteria El Martillo,Cordoba,F001,Tornillos caja x100,5,1500.50,7502.50,Transferencia,Pagado
6,V1007,NaT,Maria Gomez,Santa Fe,F002,Disco de corte,3,2500.00,7500.00,Efectivo,Pagado
7,V1008,2026-05-08,Electricidad Lopez,Entre Rios,F005,Cinta aisladora,12,1500.00,18000.00,Transferencia,Pendiente
8,V1009,2026-09-05,Construcciones Sur,Buenos Aires,F006,Martillo,2,12500.00,25000.00,Cuenta corriente,Pendiente
9,V1010,2026-05-10,Juan Perez,Buenos Aires,F003,Guantes de trabajo,2,3200.00,6400.00,Efectivo,Pagado
10,V1011,2026-05-11,Pintureria Color Norte,Mendoza,F007,Pintura látex 4L,3,18500.75,55502.25,Tarjeta,Pagado
11,V1012,2026-05-12,Maria Gomez,Santa Fe,F006,Martillo,1,12500.00,12500.00,No especificado,Pendiente
12,V1013,NaT,Ferreteria El Martillo,Cordoba,F004,Taladro eléctrico,1,85000.00,85000.00,Transferencia,Pagado
13,V1014,2026-05-13,Electricidad Lopez,Entre Rios,F008,Cable rollo 100m,2,45.00,90.00,Transferencia,Pagado
14,V1015,2026-05-14,Corralon San Jose,NaN,F001,Tornillos caja x100,8,1500.50,12004.00,Cuenta corriente,Pendiente
15,V1016,2026-05-15,Juan Perez,Buenos Aires,F002,Disco de corte,4,2500.00,10000.00,Tarjeta,Pagado
16,V1017,2026-05-16,Pintureria Color Norte,Mendoza,F007,Pintura látex 4L,2,18500.75,37001.50,Efectivo,Pagado
17,V1018,2026-05-17,Construcciones Sur,Buenos Aires,F008,Cable rollo 100m,1,NaN,45000.00,Cuenta corriente,Pendiente
18,V1019,2026-05-18,Maria Gomez,Santa Fe,F005,Cinta aisladora,5,1500.00,7500.00,Transferencia,Pagado
19,V1020,2026-05-19,Corralon San Jose,Buenos Aires,F006,Martillo,3,12500.00,37500.00,No especificado,Pendiente

In [28]:
# Automatizar: Si el cliente es Corralon San Jose y la provincia es NaN, ponerle Buenos Aires
df_datosSucios.loc[
    (df_datosSucios["cliente"] == "Corralon San Jose") & (df_datosSucios["provincia"].isna()), 
    "provincia"
] = "Buenos Aires"


df_datosSucios.head(20)

,id_venta,fecha_venta,cliente,provincia,sku,producto,cantidad,precio_unitario,monto_total,metodo_pago,estado_pago
0,V1001,2026-02-05,Juan Perez,Buenos Aires,F001,Tornillos caja x100,2,1500.50,3001.00,Efectivo,Pagado
1,V1002,2026-05-03,Ferreteria El Martillo,Cordoba,F002,Disco de corte,10,2500.00,25000.00,Transferencia,Pagado
2,V1003,2026-05-04,Maria Gomez,Santa Fe,F003,Guantes de trabajo,4,3200.00,12800.00,Tarjeta,Pagado
3,V1004,2026-05-05,Construcciones Sur,Buenos Aires,F004,Taladro eléctrico,1,85000.00,85000.00,Cuenta corriente,Pendiente
4,V1005,2026-05-06,Juan Perez,Buenos Aires,F005,Cinta aisladora,6,1500.00,9000.00,No especificado,Pagado
5,V1006,2026-07-05,Ferreteria El Martillo,Cordoba,F001,Tornillos caja x100,5,1500.50,7502.50,Transferencia,Pagado
6,V1007,NaT,Maria Gomez,Santa Fe,F002,Disco de corte,3,2500.00,7500.00,Efectivo,Pagado
7,V1008,2026-05-08,Electricidad Lopez,Entre Rios,F005,Cinta aisladora,12,1500.00,18000.00,Transferencia,Pendiente
8,V1009,2026-09-05,Construcciones Sur,Buenos Aires,F006,Martillo,2,12500.00,25000.00,Cuenta corriente,Pendiente
9,V1010,2026-05-10,Juan Perez,Buenos Aires,F003,Guantes de trabajo,2,3200.00,6400.00,Efectivo,Pagado
10,V1011,2026-05-11,Pintureria Color Norte,Mendoza,F007,Pintura látex 4L,3,18500.75,55502.25,Tarjeta,Pagado
11,V1012,2026-05-12,Maria Gomez,Santa Fe,F006,Martillo,1,12500.00,12500.00,No especificado,Pendiente
12,V1013,NaT,Ferreteria El Martillo,Cordoba,F004,Taladro eléctrico,1,85000.00,85000.00,Transferencia,Pagado
13,V1014,2026-05-13,Electricidad Lopez,Entre Rios,F008,Cable rollo 100m,2,45.00,90.00,Transferencia,Pagado
14,V1015,2026-05-14,Corralon San Jose,Buenos Aires,F001,Tornillos caja x100,8,1500.50,12004.00,Cuenta corriente,Pendiente
15,V1016,2026-05-15,Juan Perez,Buenos Aires,F002,Disco de corte,4,2500.00,10000.00,Tarjeta,Pagado
16,V1017,2026-05-16,Pintureria Color Norte,Mendoza,F007,Pintura látex 4L,2,18500.75,37001.50,Efectivo,Pagado
17,V1018,2026-05-17,Construcciones Sur,Buenos Aires,F008,Cable rollo 100m,1,NaN,45000.00,Cuenta corriente,Pendiente
18,V1019,2026-05-18,Maria Gomez,Santa Fe,F005,Cinta aisladora,5,1500.00,7500.00,Transferencia,Pagado
19,V1020,2026-05-19,Corralon San Jose,Buenos Aires,F006,Martillo,3,12500.00,37500.00,No especificado,Pendiente

In [29]:
# Eliminar las filas que no tienen fecha de venta (los NaT)
df_datosSucios = df_datosSucios.dropna(subset=["fecha_venta"])

# Verificamos cuántas filas nos quedaron limpias
print(f"Total de filas limpias y listas: {len(df_datosSucios)}")


df_datosSucios.head(15)

Total de filas limpias y listas: 32

,id_venta,fecha_venta,cliente,provincia,sku,producto,cantidad,precio_unitario,monto_total,metodo_pago,estado_pago
0,V1001,2026-02-05,Juan Perez,Buenos Aires,F001,Tornillos caja x100,2,1500.50,3001.00,Efectivo,Pagado
1,V1002,2026-05-03,Ferreteria El Martillo,Cordoba,F002,Disco de corte,10,2500.00,25000.00,Transferencia,Pagado
2,V1003,2026-05-04,Maria Gomez,Santa Fe,F003,Guantes de trabajo,4,3200.00,12800.00,Tarjeta,Pagado
3,V1004,2026-05-05,Construcciones Sur,Buenos Aires,F004,Taladro eléctrico,1,85000.00,85000.00,Cuenta corriente,Pendiente
4,V1005,2026-05-06,Juan Perez,Buenos Aires,F005,Cinta aisladora,6,1500.00,9000.00,No especificado,Pagado
5,V1006,2026-07-05,Ferreteria El Martillo,Cordoba,F001,Tornillos caja x100,5,1500.50,7502.50,Transferencia,Pagado
7,V1008,2026-05-08,Electricidad Lopez,Entre Rios,F005,Cinta aisladora,12,1500.00,18000.00,Transferencia,Pendiente
8,V1009,2026-09-05,Construcciones Sur,Buenos Aires,F006,Martillo,2,12500.00,25000.00,Cuenta corriente,Pendiente
9,V1010,2026-05-10,Juan Perez,Buenos Aires,F003,Guantes de trabajo,2,3200.00,6400.00,Efectivo,Pagado
10,V1011,2026-05-11,Pintureria Color Norte,Mendoza,F007,Pintura látex 4L,3,18500.75,55502.25,Tarjeta,Pagado
11,V1012,2026-05-12,Maria Gomez,Santa Fe,F006,Martillo,1,12500.00,12500.00,No especificado,Pendiente
13,V1014,2026-05-13,Electricidad Lopez,Entre Rios,F008,Cable rollo 100m,2,45.00,90.00,Transferencia,Pagado
14,V1015,2026-05-14,Corralon San Jose,Buenos Aires,F001,Tornillos caja x100,8,1500.50,12004.00,Cuenta corriente,Pendiente
15,V1016,2026-05-15,Juan Perez,Buenos Aires,F002,Disco de corte,4,2500.00,10000.00,Tarjeta,Pagado
16,V1017,2026-05-16,Pintureria Color Norte,Mendoza,F007,Pintura látex 4L,2,18500.75,37001.50,Efectivo,Pagado

In [30]:
# Reinicia los índices de la tabla para que queden correlativos (0, 1, 2, 3...)
df_datosSucios = df_datosSucios.reset_index(drop=True)

df_datosSucios.head(10)

,id_venta,fecha_venta,cliente,provincia,sku,producto,cantidad,precio_unitario,monto_total,metodo_pago,estado_pago
0,V1001,2026-02-05,Juan Perez,Buenos Aires,F001,Tornillos caja x100,2,1500.50,3001.00,Efectivo,Pagado
1,V1002,2026-05-03,Ferreteria El Martillo,Cordoba,F002,Disco de corte,10,2500.00,25000.00,Transferencia,Pagado
2,V1003,2026-05-04,Maria Gomez,Santa Fe,F003,Guantes de trabajo,4,3200.00,12800.00,Tarjeta,Pagado
3,V1004,2026-05-05,Construcciones Sur,Buenos Aires,F004,Taladro eléctrico,1,85000.00,85000.00,Cuenta corriente,Pendiente
4,V1005,2026-05-06,Juan Perez,Buenos Aires,F005,Cinta aisladora,6,1500.00,9000.00,No especificado,Pagado
5,V1006,2026-07-05,Ferreteria El Martillo,Cordoba,F001,Tornillos caja x100,5,1500.50,7502.50,Transferencia,Pagado
6,V1008,2026-05-08,Electricidad Lopez,Entre Rios,F005,Cinta aisladora,12,1500.00,18000.00,Transferencia,Pendiente
7,V1009,2026-09-05,Construcciones Sur,Buenos Aires,F006,Martillo,2,12500.00,25000.00,Cuenta corriente,Pendiente
8,V1010,2026-05-10,Juan Perez,Buenos Aires,F003,Guantes de trabajo,2,3200.00,6400.00,Efectivo,Pagado
9,V1011,2026-05-11,Pintureria Color Norte,Mendoza,F007,Pintura látex 4L,3,18500.75,55502.25,Tarjeta,Pagado

In [31]:
df_datosSucios.head(20)

,id_venta,fecha_venta,cliente,provincia,sku,producto,cantidad,precio_unitario,monto_total,metodo_pago,estado_pago
0,V1001,2026-02-05,Juan Perez,Buenos Aires,F001,Tornillos caja x100,2,1500.50,3001.00,Efectivo,Pagado
1,V1002,2026-05-03,Ferreteria El Martillo,Cordoba,F002,Disco de corte,10,2500.00,25000.00,Transferencia,Pagado
2,V1003,2026-05-04,Maria Gomez,Santa Fe,F003,Guantes de trabajo,4,3200.00,12800.00,Tarjeta,Pagado
3,V1004,2026-05-05,Construcciones Sur,Buenos Aires,F004,Taladro eléctrico,1,85000.00,85000.00,Cuenta corriente,Pendiente
4,V1005,2026-05-06,Juan Perez,Buenos Aires,F005,Cinta aisladora,6,1500.00,9000.00,No especificado,Pagado
5,V1006,2026-07-05,Ferreteria El Martillo,Cordoba,F001,Tornillos caja x100,5,1500.50,7502.50,Transferencia,Pagado
6,V1008,2026-05-08,Electricidad Lopez,Entre Rios,F005,Cinta aisladora,12,1500.00,18000.00,Transferencia,Pendiente
7,V1009,2026-09-05,Construcciones Sur,Buenos Aires,F006,Martillo,2,12500.00,25000.00,Cuenta corriente,Pendiente
8,V1010,2026-05-10,Juan Perez,Buenos Aires,F003,Guantes de trabajo,2,3200.00,6400.00,Efectivo,Pagado
9,V1011,2026-05-11,Pintureria Color Norte,Mendoza,F007,Pintura látex 4L,3,18500.75,55502.25,Tarjeta,Pagado
10,V1012,2026-05-12,Maria Gomez,Santa Fe,F006,Martillo,1,12500.00,12500.00,No especificado,Pendiente
11,V1014,2026-05-13,Electricidad Lopez,Entre Rios,F008,Cable rollo 100m,2,45.00,90.00,Transferencia,Pagado
12,V1015,2026-05-14,Corralon San Jose,Buenos Aires,F001,Tornillos caja x100,8,1500.50,12004.00,Cuenta corriente,Pendiente
13,V1016,2026-05-15,Juan Perez,Buenos Aires,F002,Disco de corte,4,2500.00,10000.00,Tarjeta,Pagado
14,V1017,2026-05-16,Pintureria Color Norte,Mendoza,F007,Pintura látex 4L,2,18500.75,37001.50,Efectivo,Pagado
15,V1018,2026-05-17,Construcciones Sur,Buenos Aires,F008,Cable rollo 100m,1,NaN,45000.00,Cuenta corriente,Pendiente
16,V1019,2026-05-18,Maria Gomez,Santa Fe,F005,Cinta aisladora,5,1500.00,7500.00,Transferencia,Pagado
17,V1020,2026-05-19,Corralon San Jose,Buenos Aires,F006,Martillo,3,12500.00,37500.00,No especificado,Pendiente
18,V1021,2026-05-20,Ferreteria El Martillo,Cordoba,F003,Guantes de trabajo,6,3200.00,19200.00,Tarjeta,Pagado
19,V1023,2026-05-21,Juan Perez,Buenos Aires,F001,Tornillos caja x100,3,150050.00,450150.00,Efectivo,Pagado

In [32]:
from sqlalchemy import create_engine

print("¡Librería SQLAlchemy importada correctamente!")

¡Librería SQLAlchemy importada correctamente!

In [33]:
# Creamos un motor (engine) que va a generar una base de datos llamada 'ventas_ferreteria.db'
# Si el archivo no existe, SQLite lo crea automáticamente en tu carpeta de trabajo.
engine = create_engine('sqlite:///ventas_ferreteria.db', echo=False)

print("¡Motor de base de datos SQLite creado con éxito!")

¡Motor de base de datos SQLite creado con éxito!

In [34]:
# Nombre que tendrá nuestra tabla dentro de SQLite
nombre_tabla = "tb_ventas"

# Volcamos el DataFrame a la base de datos
df_datosSucios.to_sql(
    name=nombre_tabla, 
    con=engine, 
    if_exists='replace', # Si la tabla ya existe, la reemplaza por la nueva limpia
    index=False          # Indicamos que no guarde el índice numérico viejo de pandas
)

print(f"¡Éxito! Tu tabla '{nombre_tabla}' fue cargada correctamente en SQLite.")

¡Éxito! Tu tabla 'tb_ventas' fue cargada correctamente en SQLite.

In [35]:
# 1. Rellenar precio_unitario dividiendo monto_total por cantidad para V1018 y V1024
# (Asegúrate de ver las cantidades de esas filas en tu DataFrame para que la división sea exacta, o podemos hacerlo automático)

# Si querés hacerlo de forma automática para cualquier fila donde precio_unitario sea NaN y monto_total y cantidad existan:
df_datosSucios.loc[df_datosSucios["precio_unitario"].isna(), "precio_unitario"] = (
    df_datosSucios["monto_total"] / df_datosSucios["cantidad"]
)

# 2. Volvemos a correr la carga a SQLite para actualizar la base de datos con estos dos arreglos
df_datosSucios.to_sql(
    name="tb_ventas", 
    con=engine, 
    if_exists='replace', 
    index=False
)

print("¡Precios unitarios corregidos y base de datos actualizada con éxito!")

¡Precios unitarios corregidos y base de datos actualizada con éxito!

In [36]:
from sqlalchemy import create_engine, text

# 1. Conectamos al motor de SQLite
engine = create_engine('sqlite:///ventas_ferreteria.db')

# 2. Ejecutamos la sentencia SQL de actualización (UPDATE)
# (Reemplazá 'Buenos Aires' o la provincia que corresponda al cliente de la venta V1027)
query_update = text("""
    UPDATE tb_ventas 
    SET provincia = 'Buenos Aires' 
    WHERE id_venta = 'V1027';
""")

# Abrimos una conexión para ejecutar la modificación de datos de forma segura
with engine.begin() as conn:
    conn.execute(query_update)

print("¡Registro V1027 actualizado con éxito en la base de datos!")

¡Registro V1027 actualizado con éxito en la base de datos!

In [45]:
import pandas as pd
from sqlalchemy import create_engine

# 1. Nos conectamos a nuestra base de datos SQLite existente
engine = create_engine('sqlite:///ventas_ferreteria.db')

# 2. Escribimos nuestra consulta SQL pura
query_provincia = """
    SELECT 
        provincia, 
        COUNT(id_venta) AS cantidad_ventas,
        SUM(monto_total) AS facturacion_total,
        ROUND(AVG(monto_total), 2) AS ticket_promedio
    FROM tb_ventas
    GROUP BY provincia
    ORDER BY facturacion_total DESC;
"""

# 3. Ejecutamos la query utilizando Pandas como puente para visualizarla prolijo
df_resultado = pd.read_sql(query_provincia, con=engine)

# Mostramos el resultado
df_resultado

      provincia  cantidad_ventas  facturacion_total  ticket_promedio
0  Buenos Aires               15         950560.000         63370.67
1      Santa Fe                5         130300.000         26060.00
2       Mendoza                4         111078.503         27769.63
3       Cordoba                4          66702.500         16675.63
4    Entre Rios                4          38190.000          9547.50

In [47]:
import pandas as pd
from sqlalchemy import create_engine

# 1. Nos conectamos a nuestra base de datos SQLite existente
engine = create_engine('sqlite:///ventas_ferreteria.db')

queryproducto = """  
SELECT 
    producto,                             
    SUM(cantidad) AS unidades_vendidas,   
    SUM(monto_total) AS facturacion_total
FROM tb_ventas                            
GROUP BY producto                          
ORDER BY facturacion_total DESC;           


""" 

# 3. Ejecutamos la query utilizando Pandas como puente para visualizarla prolijo
df_productos = pd.read_sql(queryproducto, con=engine)

# Mostramos el resultado
df_productos

              producto  unidades_vendidas  facturacion_total
0  Tornillos caja x100                 28         487662.500
1    Taladro eléctrico                  4         340000.000
2             Martillo                 11         137500.000
3     Pintura látex 4L                 10         111078.503
4       Disco de corte                 27          67500.000
5      Cinta aisladora                 40          60000.000
6   Guantes de trabajo                 15          48000.000
7     Cable rollo 100m                  3          45090.000

In [46]:
import pandas as pd
from sqlalchemy import create_engine

# 1. Nos conectamos a nuestra base de datos SQLite existente
engine = create_engine('sqlite:///ventas_ferreteria.db')

querymetodopago = """  
SELECT 
    metodo_pago,
    COUNT(id_venta) AS cantidad_transacciones
FROM tb_ventas
GROUP BY metodo_pago
ORDER BY cantidad_transacciones DESC
limit 3       


""" 

# 3. Ejecutamos la query utilizando Pandas como puente para visualizarla prolijo
df_resultadopago = pd.read_sql(querymetodopago, con=engine)

# Mostramos el resultado
df_resultadopago

        metodo_pago  cantidad_transacciones
0     Transferencia                       8
1          Efectivo                       7
2  Cuenta corriente                       7

In [41]:
import pandas as pd
from sqlalchemy import create_engine

# 1. Nos conectamos a nuestra base de datos SQLite existente
engine = create_engine('sqlite:///ventas_ferreteria.db')

query_ticket_cliente = """
    SELECT 
        cliente,
        COUNT(id_venta) AS total_compras,
        SUM(monto_total) AS facturacion_total,
        ROUND(AVG(monto_total), 2) AS ticket_promedio
    FROM tb_ventas
    GROUP BY cliente
    ORDER BY ticket_promedio DESC;
"""

df_ticket_cliente = pd.read_sql(query_ticket_cliente, con=engine)
df_ticket_cliente

                  cliente  total_compras  facturacion_total  ticket_promedio
0              Juan Perez              6         491051.000         81841.83
1       Corralon San Jose              4         234509.000         58627.25
2      Construcciones Sur              5         225000.000         45000.00
3  Pintureria Color Norte              4         111078.503         27769.63
4             Maria Gomez              5         130300.000         26060.00
5  Ferreteria El Martillo              4          66702.500         16675.63
6      Electricidad Lopez              4          38190.000          9547.50

In [42]:
import pandas as pd
from sqlalchemy import create_engine

# 1. Nos conectamos a nuestra base de datos SQLite existente
engine = create_engine('sqlite:///ventas_ferreteria.db')

query_evolucion_mes = """
    SELECT 
        strftime('%Y-%m', fecha_venta) AS mes_venta,
        COUNT(id_venta) AS cantidad_ventas,
        SUM(monto_total) AS facturacion_mensual,
        ROUND(AVG(monto_total), 2) AS ticket_promedio_mensual
    FROM tb_ventas
    GROUP BY mes_venta
    ORDER BY mes_venta ASC;
"""

df_evolucion = pd.read_sql(query_evolucion_mes, con=engine)
df_evolucion

  mes_venta  cantidad_ventas  facturacion_mensual  ticket_promedio_mensual
0   2026-02                1             3001.000                  3001.00
1   2026-05               29          1261327.503                 43494.05
2   2026-07                1             7502.500                  7502.50
3   2026-09                1            25000.000                 25000.00